apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        app: {{ template "fullname" . }}
        release: {{ .Release.Name }}
    spec:
      hostNetwork: {{ .Values.deployment.hostNetwork }}
      containers:
      - image: {{ .Values.image }}
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        name: {{ template "fullname" . }}
        command: ["/usr/sbin/mosquitto", "-c", "/mosquitto/config/mosquitto.conf"]
        ports:
        - containerPort: 1883
          name: "mqtt"
        - containerPort: 9090
          name: "websocket"
        volumeMounts:
          - name: mosquitto-conf
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
            readOnly: true
        {{- range $index,$item := .Values.extraConfig }}
          - name: mosquitto-conf
            subPath: extra-config-{{ $index }}
            readOnly: true
            mountPath: /mosquitto/config/{{ $item.filename }}
        {{- end }}
          - name: mosquitto-data
            mountPath: /mosquitto/data
            subPath: mosquitto/data
        {{- with .Values.extraMounts }}
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.deployment.probes }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.deployment.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      volumes:
      - name: mosquitto-conf
        configMap:
          name: {{ template "fullname" . }}
      - name: mosquitto-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "fullname" . }}
      {{- else }}
        emptyDir: {}
      {{- end -}}
      {{- with .Values.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
