# Default values for mosquitto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: smizy/mosquitto:1.4.15-alpine

imagePullPolicy: IfNotPresent

service:
  enabled: true
  type: "ClusterIP"

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 2Gi
  storageClass: standard

deployment:
  hostNetwork: false
  probes:
    livenessProbe:
      tcpSocket:
        port: 9090
      initialDelaySeconds: 5
      periodSeconds: 1
    readinessProbe:
      tcpSocket:
        port: 9090
      initialDelaySeconds: 3
      periodSeconds: 3
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 100m
      memory: 256Mi

config: |-
  log_dest stdout
  listener 1883
  listener 9090
  protocol websockets

extraConfig: []
# #  allow_anonymous false
# #  password_file auth/passwordfile
# - filename: auth/passwordfile
#   content: |-
#     user:$6$LpvFTnfXz1634JoO$oZjduJFV2wRfBL2Fn+Re5422DeL90dcx+M/jSHRfRvFVhUPwQxHmw64sD7aw+272JJSKbgiVjJXjRQ943ucb4g==
#     test:$6$RFU4TM5lSR6ZvjlM$sxK8rndx2tdgUJyeN1Wg/w20FATUA3gJr6yxvLzc6MbUO8/asfxYq02/PZFQKGheIK30bi/pmWDWaE+Gt+3IBw==

extraVolumes: []
# - name: tls-cert
#   secret:
#     secretName: mosquitto-tls-cert

extraMounts: []
# - name: mosquitto-tls-cert
#   readOnly: true
#   mountPath: /mosquitto/config/tls
